### ISSUE TITLE
你妈死了，傻逼汉奸

### ISSUE THREAD

**Issue by explorer3039** [zaohmeing/21-#281]
中国共产党万岁！中华人民共和国万岁！

**Comment by kevin126ckw** [comment]
中华人民共和国万岁！

**Comment by NuclearReactor314** [comment]
笑死我了，到现在还支持中共真是可笑。

**Comment by explorer3039** [comment]
敢不敢去中国各大平台说？低智商汉奸

**Comment by explorer3039** [comment]
是个人都知道GitHub是交流技术，编程用的，发政治别他妈在GitHub发，是不是因为你访问你全家的时候报空指针，才来GitHub上bb的啊

**Comment by NuclearReactor314** [comment]
我又不在中国，你跟我叫什么

**Comment by NuclearReactor314** [comment]
你共封了所有东西，也不差GitHub这一个了，去跟你共狗叫吧

**Comment by explorer3039** [comment]
懒得和你扣字了，给这种人对骂就是浪费生命

**Comment by kevin126ckw** [comment]
真的，我对这种死汉奸想顺着网线阴暗的爬行到他家去，他就是觉得github是外国平台管的少还没被墙，就发表反动言论，搞得一个好好的技术交流网站被污染

**Comment by explorer3039** [comment]
发表这些言论，你有人证，物证吗？还有你这垃圾排版，看完后我赶快看了几篇爱国教育文章洗洗我的眼睛

**Comment by explorer3039** [comment]
> 真的，我对这种死汉奸想顺着网线阴暗的爬行到他家去，他就是觉得github是外国平台管的少还没被墙，就发表反动言论，搞得一个好好的技术交流网站被污染

对

**Comment by explorer3039** [comment]
文章放到gitignore里面，是不是因为你妈死了想让人忽略啊

**Comment by kevin126ckw** [comment]
我都没敢看他这坨屎repo，无中生有暗度陈仓凭空想象凭空捏造，没有中国共产党他现在还在被抓去给老佛爷修院子，修完还得去当太监......拉的屎，中国共产党好不容易让世界和平（至少中国境内和平）了，我都不明白是哪个访问一下都得抛出空指针错误的不明生物生的

**Comment by explorer3039** [comment]
言论没有一点依据，还有你这垃圾排版，看完后我赶快看了几篇爱国教育文章洗洗我的眼睛，是不是要让110给你用markdown排一下版？

**Comment by NuclearReactor314** [comment]
不愧是支那人

**Comment by explorer3039** [comment]
我中国人我自豪

**Comment by kevin126ckw** [comment]
我中国人我自豪，中国共产党万岁!

**Comment by oneHiking** [comment]
傻逼玩意儿，耽误老子搜索资料，不管你是低级黑还是高级红，都给老子死远点  滚你妈卖批

**Comment by finedaysunrise** [comment]
中国人民万岁!中华人民共和国万岁!中国共产党万岁!

**Comment by finedaysunrise** [comment]
> 不愧是支那人
狗汉奸我操你妈臭逼

**Comment by finedaysunrise** [comment]
狗汉奸我操你妈臭逼，全家死光的畜生东西，技术交流网站看到你这畜生是真的晦气
